export interface UserInfo {
    userId: string,
    patientId: string,
    firstName: string,
    lastName: string,
    email: string,
    mobileNumber: string,
    countryCode:string,
    dateofBirth: string,
    gender: number,
    SocialLoginId: number,
    SocialLoginType: string,
    IsEmailVerified: string,
    IsPhoneVerified: boolean,
    uhid: string,
    AuthTokenForPR:string,
    AskApolloReferenceIdForSelf?:string,
    imageUrl?:String,
    pn?:string,
    PatientOrigin:any
}

export interface pastAppointmentDetails
{
    Qualification:string;
    doctorId: number,
    doctorProfileURL: string,
    doctorName: string,
    appointmentDate: string,
    appointmentDay: string,
    slotTime: string,
    specialityId: number,
    speciality: string,
    appointmentId: number,
    appointmentTypeId: number,
    status: string,
    doctorExperience: number,
    hospitalId: number,
    hospitalName: string,
    cityId: number,
    cityName: string,
    bookedByName: string,
    createdBy: number,
    bookedDate: string,
    PatientSpecificAppointmentDetails: {
        userId: number,
        patientId: number,
        patientName: string,
        mobileNo: string,
        gender: string,
        age: number,
        email: string,
        uAID: string,
        uHID: string,
        prnNumber: string
    }
}
export interface futureAppointmentDetails
{
    Qualification:string;
    doctorId: number,
    doctorProfileURL: string,
    doctorName: string,
    appointmentDate: string,
    appointmentDay: string,
    slotTime: string,
    specialityId: number,
    speciality: string,
    appointmentId: number,
    appointmentTypeId: number,
    status: string,
    doctorExperience: number,
    hospitalId: number,
    hospitalName: string,
    cityId: number,
    cityName: string,
    bookedByName: string,
    createdBy: number,
    bookedDate: string,
    PatientSpecificAppointmentDetails: {
        userId: number,
        patientId: number,
        patientName: string,
        mobileNo: string,
        gender: string,
        age: number,
        email: string,
        uAID: string,
        uHID: string,
        prnNumber: string
    }
}

export interface aaToken {
    AskApolloReferenceIdForSelf: string,
    OnlineConsultToken: string
}

// gender: "male",
// dob: "18-03-1970 06:30 PM",
export interface UHID {
    userId?: string,
    uhid?: string,
    hasLabResult?: string,
    firstName?: string,
    middleName?: string,
    lastName?: string,
    fullName?: string,
    siteName?: string,
    activationStatus?: string,
    lastLogOn?: string,
    registrationDate?: string,
    mobileNumber?: string,
    activationDate?: string,
    status?: string,
    tat?: string,
    loginId?: string,
    importedDate?: string,
    gender?: string,
    dob?: any,
    email?: string,
    address?: string,
    city?: string,
    state?: string,
    age?: number,
    relationship?: string,
    isRelation?:boolean,
    patRelationId?:any
}



export interface topspecialityList {

    topspecialityId: number,
    speciality: string,
    imageUrl: string,
    specialiryId: number,
    createdDate: string
}
export interface topDoctorsAnonymous {

    DoctorId: number,
    UserId: number,
    FirstName: string,
    LastName: string,
    Speciality: string,
    Gender: string,
    HospitalName: string,
    CityName: string,
    LanguagesKnown: number,
    Experience: number,
    Achievements: string,
    Publications: string,
    ProfessionalMemberships: string,
    DOB: string,
    Tariff: string,
    CompletePhotoUrl: string,
    PhotoUrl: string,
    Email: string,
    MobileNumber: number,
    Qualification: string,
    SpecialityId: number,
    StateName: string,
    CountryId: number,
    CountryName: string,
    HospitalId: number,
    RegistrationNo: number,
    DayofWeek: string,
    SemContent: number,
    Doctors: string,
    USD: number,
    ConsEmail: string,
    Video: string,
    Voice: string,
    HasEmail: string,
    HasVideo: string,
    HasVoice: string
}
export interface ocUpcomingAppointmentDetails {
    $id:number,
    doctorname:string,
    DoctorId:string,
    Photo:string,
    YearsOfExperience:number,
    Speciality:string,
    AppointmentDate:string,
    AppointmentTime:string,
    IsCaseClosed:boolean,
    VisitId:number,
    Uhid:string,
    Category:string, //Video,Voice,Email
    AppointmentId:number,
    IsRefund:boolean,
    consultationType:string,
    IsPaymentRequired:boolean,
    IsPaid:boolean,
    amount:number,
    Position:string,
    IsReview:boolean,
    ReviewReferenceVisitId:number,
    CreatedDate:string,
    CreatedTime:string,
    IsPrescriptionGiven:boolean,
    IsRescheduleRequested:boolean,
    IsPrescriptionCompleted:boolean,
    VisitStatus:string,
    IsCaseSheetSubmitted:boolean,
    Clarification:boolean,
    Feedback:boolean,
    Languages:string,
    DocGender:string,
    Qualification:string,
    IsCancelled:boolean,
    AppointmentDateTime:string,
    HospitalName:string,
    AppointmentStatus:string,
    DueAmount:number,
    EdocSpecialityId:number,
    EdocDoctorId:number,
    PatientName:string,
    DayofWeek:string,
    CurrencyFormat:string,
    Gender:string,
    Age:number,
    CaseSheetVersion:string
}

export interface ocpastAppointmentDetails 
{
    $id:string,
    Age:number,
    AppointmentDate:string,
    AppointmentDateTime:string,
    AppointmentId:number,
    AppointmentStatus:string,
    AppointmentTime:string,
    Category:string,
    Clarification:string,
    CreatedDate:string,
    CreatedTime:string,
    DayofWeek:string,
    DocGender:string,
    DoctorId:string,
    DueAmount:number,
    EdocDoctorId:number,
    EdocSpecialityId:number,
    Feedback:string,
    Gender:string,
    HospitalId:number,
    HospitalName:string,
    IsCancelled:boolean,
    IsCaseClosed:boolean,
    IsCaseSheetSubmitted:boolean,
    IsPaid:boolean,
    IsPaymentRequired:boolean,
    IsPrescriptionCompleted:boolean,
    IsPrescriptionGiven:boolean,
    IsRefund:boolean,
    IsRescheduleRequested:boolean,
    IsReview:boolean,
    Languages:string,
    LocationId:number,
    OrderId:string,
    PatientName:string,
    PharmacyResponce:string,
    Photo:string,
    Position:string,
    Qualification:string,
    ReviewDays:number,
    ReviewReferenceVisitId:number,
    Speciality:string,
    SpecialityId:number,
    Uhid:string,
    VisitId:number,
    VisitStatus:string,
    YearsOfExperience:string,
    amount:number,
    consultationType:string,
    doctorname:string,
    CaseSheetVersion:string
}
export interface AppointmentDetailsByAppointmentId {

    $id: string,
    doctorname: string,
    DoctorId: string,
    Photo: string,
    YearsOfExperience: string,
    Speciality: string,
    AppointmentDate: string,
    AppointmentTime: string,
    IsCaseClosed: string,
    VisitId: string,
    Uhid: string,
    Category: string,
    AppointmentId: string,
    IsRefund: string,
    consultationType: string,
    HospitalName: string,
    AppointmentStatus: string,
    DueAmount: string,
    EdocSpecialityId: string,
    EdocDoctorId: string,
    IsPaymentRequired: string,
    IsPaid: string,
    amount: string,
    Position: string,
    IsReview: string,
    ReviewReferenceVisitId: string,
    CreatedDate: string,
    CreatedTime: String,
    IsPrescriptionGiven: string,
    IsRescheduleRequested: String,
    IsPrescriptionCompleted: string,
    VisitStatus: string,
    IsCaseSheetSubmitted: String,
    Clarification: string,
    Feedback: string,
    Languages: string,
    DocGender: string,
    Qualification: string,
    IsCancelled: string,
    AppointmentDateTime: string,
    PatientName: string,
    DayofWeek: string,
    CurrencyFormat: string,
    Gender: string,
    Age: string,
}

export interface OCUserInfo {
    FirstName: string,
    LastName: string,
    Mobileno: number,
    Age: string,
    Adddress: string,
    CountryCode: string,
    CountryName: string,
    State: string,
    City: string,
    Pin: string,
    EmailId: string,
    Gender: string,
    Uhid: string,
    DOB: string,
    IsConsentAccept: string,
    ImageName: string,
    CreatedBy: string,
    CreatedDate: string,
    PatientId: string,
    AlternateNumber: string,
    PhotoExt: string,
    Photocontent: string,
    CountryId: number,
    StateId: number,
    CityId: number,
    MMUhid: string,
    BloodGroup:string
}

export interface OrderMedicines 
{
    SNO: number,
    FirstName: string,
    LastName: string,
    Gender: string,
    Age: number,
    MobileNo: number,
    City: string,
    Zip: number,
    Address: string,
    MailID: string,
    OrderID: number,
    ShippingMethod: string,
    PaymentMethod: string,
    SiteID: number,
    VendorName: string,
    URL: string,
    Source: string,
    AppointmentId: number,
    CreatedDate: string,
    PharmacyResponce: string,
    IsActive: boolean,
    OrderStatus: string,
    SourceApp: string,
    CouponCode: string,
    OTCCartData: string,
    PharmacyOrderId: number,
    PharmacyOrderValue: number,
    PharmacyOrderRemarks: string,
    PharmacyStoreCode: string,
    EntityKey:{
        EntityContainerName: string,
        EntityKeyValues:{
            
        },
        EntitySetName: string,
        IsTemporary: boolean
    }
}
export interface AlexaSourceResponse
{
    Name:string,
    Email:string,
    PhoneNumber:string,
    PhotoURL:string,
    Gender:string,
    MarritalStatus:string,
    DOB:string,
    PhoneNumberVerified:boolean,
    EmailVerified:boolean,
    Token:string,
    Availbility:string,
    PatientId:string,
    PatientOrigin:string,
    Country:number,
    MMUhid:string,
    CountryCode:number,
    Alexa:boolean
}

export interface RelativeData
{
    Age: number,
    CreatedBy: string,
    CreatedDate: string,
    Dob: string,
    FirstName: string,
    Gender: string,
    ImageContent: string,
    ImageFileName: string,
    IsActive: boolean,
    LastName: string,
    MMUHID: string,
    ModifiedBy: string,
    ModifiedDate: string,
    PatRelationId: number,
    PatientId: string,
    PhotoContent: string,
    PhotoExt: string,
    PhotoName: string,
    Relation: string,
    RelationId: number,
    Uhid: string
}

export interface Clarification
{
    $id:string,
    ClarificationCategoryId:number,
    ClarificationCategory:string,
    IsActive:boolean,
    CreatedBy:string,
    CreatedDate:string,
}

export interface DownloadPrescription
{
    VisitId:string,
    FileName:string,
    FileFormat:string,
    File_Size:number,
    File_Content:string,
}

export interface CasesheetDetails
{
    PatientId:string,
    DoctorId:string,
    LocationId:number,
    SpecialityId:number,
    HospitalId:number,
    MerchantId:string,
    CategoryId:number,
    Feet:string,
    Inches:string,
    Height:string,
    Weight:string,
    PresentComplains:string,
    PastHistory:string,
    FamilyHistory:string,
    age:string,
    gender:string,
    occupation:string,
    foodPreferanceValue:string,
    foodPreferanceText:string,
    tobacco:string,
    tobaccodesc:string,
    alcohol:string,
    alcoholdesc:string,
    Allergies:string,
    AnyOtherTreatmentUnderTaken:string,
    OtherDetails:string,
    Consultationtypeid:number,
    RequestType:string,
    RelationId:number,
    PatientName:string,
    PatientImageUrl:string,
    PatientUHID:string,
    bloodgroup:string,
    AllergiesArray?:any[]
    MedictionsArray?:any[]
}

export interface PrescriptionDetails
{
    AppointmentId:number,
    FirstName:string,
    LastName:string,
    Gender:string,
    Age:number,
    Uhid:string,
    DateOfBirth:string,
    Address:string,
    MobileNO:string,
    EmailId:string,
    Height:string,
    Weight:string,
    DoctorName:string,
    Registrationnumber:string,
    Qualification:string,
    HospitalName:string,
    Presentcomplaints:string,
    ProvisionalDiagnosis:string,
    AdviceAndTreatment:string,
    RefPhysicalAppointment:boolean,
    RefSpecialistOpinion:boolean,
    SuggestedSpeciality:boolean,
    Speciality:string,
    Signature:string,
    PublicKey:string,
    Signedby:string,
    CreatedDate:string,
    ChangeMedium:boolean
}
export interface Attachments
{
    Sno:number,
    DocumentName:string,
    FileName:string,
    Description:string,
    VisitId:number,
    DocumentId:number,
    FileFormat:string,
    size:number
}
export interface appointmentDetails {
    $id:number,
    doctorname:string,
    DoctorId:string,
    Photo:string,
    YearsOfExperience:number,
    Speciality:string,
    SpecialityId:string,
    AppointmentDate:string,
    AppointmentTime:string,
    IsCaseClosed:boolean,
    VisitId:number,
    Uhid:string,
    DisplayDate:string,
    DisplayTime:string,
    Category:string, //Video,Voice,Email
    AppointmentId:number,
    IsRefund:boolean,
    consultationType:string,
    IsPaymentRequired:boolean,
    IsPaid:boolean,
    amount:number,
    Position:string,
    IsReview:boolean,
    ReviewReferenceVisitId:number,
    CreatedDate:string,
    CreatedTime:string,
    IsPrescriptionGiven:boolean,
    IsRescheduleRequested:boolean,
    IsPrescriptionCompleted:boolean,
    VisitStatus:string,
    IsCaseSheetSubmitted:boolean,
    Clarification:boolean,
    Feedback:boolean,
    Languages:string,
    DocGender:string,
    Qualification:string,
    IsCancelled:boolean,
    AppointmentDateTime:string,
    HospitalName:string,
    AppointmentStatus:string,
    DueAmount:number,
    EdocSpecialityId:number,
    EdocDoctorId:number,
    PatientName:string,
    DayofWeek:string,
    CurrencyFormat:string,
    Gender:string,
    Age:number
}

export interface HospitalLatLong{
        Latitude:string,
        Longitude:string
}

